apiVersion: v1
kind: ConfigMap
metadata:
  name: example-app-1
  namespace: default
data:
  config.json: |
    {
      "environment" : "dev"
    }
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: example-app-2
  namespace: default
data:
  config.json: |
    {
      "environment" : "dev"
    }
