apiVersion: apps/v1
kind: Deployment
metadata:
  name: example-app-3
  labels:
    app: example-app-3
  namespace: default
spec:
  selector:
    matchLabels:
      app: example-app-3
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: example-app-3
    spec:
      containers:
      - name: example-app-3
        image: nileshrpatil2025/example-app-3:0e72af6
        ports:
        - containerPort: 5000
        volumeMounts:
        - name: config-volume
          mountPath: /configs/
      volumes:
      - name: config-volume
        configMap:
          name: example-app-3
