name: CI

on:
  workflow_dispatch:
    inputs:
      environment:
        type: environment
        description: Select the environment
        options:
        - Dev
        - Test
        - Prod
      boolean:
        type: boolean
        description: True or False
      choice:
        type: choice
        description: Make a choice
        options:
        - foo
        - bar
        - baz
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: code checkout
        uses: actions/checkout@v2
      - name: test        
        if: ${{ github.event.inputs.boolean == 'true' }}
        run:
          echo "boolean is ${{ github.event.inputs.boolean }}" / ${{ inputs.boolean }}
#           echo "environment is ${{ github.event.inputs.environment }} / ${{ inputs.environment }}"
#           echo "choice is ${{ github.event.inputs.choice }}" / ${{ inputs.choice }}
