name: Build Docker Image
on: workflow_dispatch
  # workflow_dispatch:
  #   inputs:
  #     service1:
  #       type: boolean
  #       description: Select Service1 to Deploy
  #     service2:
  #       type: boolean
  #       description: Select Service2 to Deploy
  # push:
  #   branches:
  #     - main
jobs:
    build:
      name: push docker image to docker hub
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3
          with:
            token: ${{ secrets.GH_TOKEN }}
            
        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v2
            
        - name: login to docker hub
          uses: docker/login-action@v2
          with:
            username: ${{secrets.DOCKERHUB_USERNAME}}
            password: ${{secrets.DOCKERHUB_PASSWORD}}

        - name: build the docker image
          id: build-docker-image
          run: |
            cd src
            ls -la 
            docker build . -f dockerfile -t nileshrpatil/example-app-1:$(git rev-parse --short HEAD)
        - name: push the docker image
          id: push-docker-image
          run: |
            TAG=$(git rev-parse --short HEAD)
            docker push ${{secrets.DOCKERHUB_USERNAME}}/example-app-1:$TAG
            sed -i "s|image:.*|image: example-app-1:$TAG|" deploy/deployment.yaml
            
        - name: Commit updated deployment.yaml
          uses: stefanzweifel/git-auto-commit-action@v5
          with:
            commit_message: "Update image tag to latest"
            file_pattern: deploy/deployment.yaml
          
        # - name: update manifest file with latest image   
        #   uses: Charlyzzz/update-k8s-image@v1.7.1
        #   with:
        #     manifest-path: ./deploy/deployment.yaml
        #     new-image-tag: latest
        #    container-name: example-app-1
