name: Build & Deploy
on: 
  # workflow_dispatch:
  #   inputs:
  #     service1:
  #       type: boolean
  #       description: Select Service1 to Deploy
  #     service2:
  #       type: boolean
  #       description: Select Service2 to Deploy
  push:
    branches:
      - main

env:
  REGISTRY: docker.io
  IMAGE_NAME: ${{ secrets.DOCKERHUB_USERNAME }}/example-app-1
  
jobs:
    build:
      name: Deploy Service1
      runs-on: ubuntu-latest
      steps:
        - name: Checkout Code
          uses: actions/checkout@v3
          with:
            token: ${{ secrets.GH_TOKEN }}
            
           
        - name: login to docker hub
          uses: docker/login-action@v2
          with:
            username: ${{secrets.DOCKERHUB_USERNAME}}
            password: ${{secrets.DOCKERHUB_PASSWORD}}

        - name: build & push the docker image
#          if: ${{ github.event.inputs.service1 == 'true' }}
          run: |
            echo "Deploying Service1..."
            TAG=$(git rev-parse --short HEAD)
            ls -la 
            docker build -t $IMAGE_NAME:$TAG ./src
            docker push $IMAGE_NAME:$TAG
            sed -i "s|image:.*|image: $IMAGE_NAME:$TAG|" deploy/deployment.yaml
            
        - name: Commit updated deployment.yaml
          uses: stefanzweifel/git-auto-commit-action@v5
          with:
            commit_message: "Update image tag to latest"
            file_pattern: deploy/deployment.yaml

          
        # - name: update manifest file with latest image   
        #   uses: Charlyzzz/update-k8s-image@v1.7.1
        #   with:
        #     manifest-path: ./deploy/deployment.yaml
        #     new-image-tag: latest
        #    container-name: example-app-1
