name: Build Docker Image
on: workflow_dispatch
  # push:
  #   branches:
  #     - main
jobs:
    build:
      name: push docker image to docker hub
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - name: login to docker hub
          id: docker-hub
          env:
            username: ${{secrets.DOCKERHUB_USERNAME}}
            password: ${{secrets.DOCKERHUB_PASSWORD}}
          run: |
            docker login -u $username -p $password 
        - name: build the docker image
          id: build-docker-image
          run: |
            cd src
            ls -la 
            docker build . -f Dockerfile -t nileshrpatil/example-app-1:latest
        - name: push the docker image
          id: push-docker-image
          run: docker push ${{secrets.DOCKERHUB_USERNAME}}/example-app-1:latest
        - name: update manifest file with latest image   
          uses: nileshrpatil/example-app-1@latest
          with:
            manifest-path: ../deploy/deployment.yaml
            new-image-tag: latest
            container-name: example-app-1
